/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminUnitsRouteImport } from './routes/admin.units'
import { Route as AdminTransfersRouteImport } from './routes/admin.transfers'
import { Route as AdminSuppliersRouteImport } from './routes/admin.suppliers'
import { Route as AdminSalesRouteImport } from './routes/admin.sales'
import { Route as AdminPurchasesRouteImport } from './routes/admin.purchases'
import { Route as AdminPaymentmethodsRouteImport } from './routes/admin.paymentmethods'
import { Route as AdminLocationsRouteImport } from './routes/admin.locations'
import { Route as AdminLedgerRouteImport } from './routes/admin.ledger'
import { Route as AdminJournalRouteImport } from './routes/admin.journal'
import { Route as AdminItemsRouteImport } from './routes/admin.items'
import { Route as AdminCustomersRouteImport } from './routes/admin.customers'
import { Route as AdminCashboxesRouteImport } from './routes/admin.cashboxes'
import { Route as AdminBatchesRouteImport } from './routes/admin.batches'
import { Route as AdminAccountsRouteImport } from './routes/admin.accounts'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUnitsRoute = AdminUnitsRouteImport.update({
  id: '/units',
  path: '/units',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTransfersRoute = AdminTransfersRouteImport.update({
  id: '/transfers',
  path: '/transfers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSuppliersRoute = AdminSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSalesRoute = AdminSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPurchasesRoute = AdminPurchasesRouteImport.update({
  id: '/purchases',
  path: '/purchases',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentmethodsRoute = AdminPaymentmethodsRouteImport.update({
  id: '/paymentmethods',
  path: '/paymentmethods',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLocationsRoute = AdminLocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLedgerRoute = AdminLedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => AdminRoute,
} as any)
const AdminJournalRoute = AdminJournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => AdminRoute,
} as any)
const AdminItemsRoute = AdminItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCashboxesRoute = AdminCashboxesRouteImport.update({
  id: '/cashboxes',
  path: '/cashboxes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBatchesRoute = AdminBatchesRouteImport.update({
  id: '/batches',
  path: '/batches',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAccountsRoute = AdminAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/accounts': typeof AdminAccountsRoute
  '/admin/batches': typeof AdminBatchesRoute
  '/admin/cashboxes': typeof AdminCashboxesRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/items': typeof AdminItemsRoute
  '/admin/journal': typeof AdminJournalRoute
  '/admin/ledger': typeof AdminLedgerRoute
  '/admin/locations': typeof AdminLocationsRoute
  '/admin/paymentmethods': typeof AdminPaymentmethodsRoute
  '/admin/purchases': typeof AdminPurchasesRoute
  '/admin/sales': typeof AdminSalesRoute
  '/admin/suppliers': typeof AdminSuppliersRoute
  '/admin/transfers': typeof AdminTransfersRoute
  '/admin/units': typeof AdminUnitsRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/accounts': typeof AdminAccountsRoute
  '/admin/batches': typeof AdminBatchesRoute
  '/admin/cashboxes': typeof AdminCashboxesRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/items': typeof AdminItemsRoute
  '/admin/journal': typeof AdminJournalRoute
  '/admin/ledger': typeof AdminLedgerRoute
  '/admin/locations': typeof AdminLocationsRoute
  '/admin/paymentmethods': typeof AdminPaymentmethodsRoute
  '/admin/purchases': typeof AdminPurchasesRoute
  '/admin/sales': typeof AdminSalesRoute
  '/admin/suppliers': typeof AdminSuppliersRoute
  '/admin/transfers': typeof AdminTransfersRoute
  '/admin/units': typeof AdminUnitsRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/accounts': typeof AdminAccountsRoute
  '/admin/batches': typeof AdminBatchesRoute
  '/admin/cashboxes': typeof AdminCashboxesRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/items': typeof AdminItemsRoute
  '/admin/journal': typeof AdminJournalRoute
  '/admin/ledger': typeof AdminLedgerRoute
  '/admin/locations': typeof AdminLocationsRoute
  '/admin/paymentmethods': typeof AdminPaymentmethodsRoute
  '/admin/purchases': typeof AdminPurchasesRoute
  '/admin/sales': typeof AdminSalesRoute
  '/admin/suppliers': typeof AdminSuppliersRoute
  '/admin/transfers': typeof AdminTransfersRoute
  '/admin/units': typeof AdminUnitsRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/admin/accounts'
    | '/admin/batches'
    | '/admin/cashboxes'
    | '/admin/customers'
    | '/admin/items'
    | '/admin/journal'
    | '/admin/ledger'
    | '/admin/locations'
    | '/admin/paymentmethods'
    | '/admin/purchases'
    | '/admin/sales'
    | '/admin/suppliers'
    | '/admin/transfers'
    | '/admin/units'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin/accounts'
    | '/admin/batches'
    | '/admin/cashboxes'
    | '/admin/customers'
    | '/admin/items'
    | '/admin/journal'
    | '/admin/ledger'
    | '/admin/locations'
    | '/admin/paymentmethods'
    | '/admin/purchases'
    | '/admin/sales'
    | '/admin/suppliers'
    | '/admin/transfers'
    | '/admin/units'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/admin/accounts'
    | '/admin/batches'
    | '/admin/cashboxes'
    | '/admin/customers'
    | '/admin/items'
    | '/admin/journal'
    | '/admin/ledger'
    | '/admin/locations'
    | '/admin/paymentmethods'
    | '/admin/purchases'
    | '/admin/sales'
    | '/admin/suppliers'
    | '/admin/transfers'
    | '/admin/units'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/units': {
      id: '/admin/units'
      path: '/units'
      fullPath: '/admin/units'
      preLoaderRoute: typeof AdminUnitsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/transfers': {
      id: '/admin/transfers'
      path: '/transfers'
      fullPath: '/admin/transfers'
      preLoaderRoute: typeof AdminTransfersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/suppliers': {
      id: '/admin/suppliers'
      path: '/suppliers'
      fullPath: '/admin/suppliers'
      preLoaderRoute: typeof AdminSuppliersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sales': {
      id: '/admin/sales'
      path: '/sales'
      fullPath: '/admin/sales'
      preLoaderRoute: typeof AdminSalesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/purchases': {
      id: '/admin/purchases'
      path: '/purchases'
      fullPath: '/admin/purchases'
      preLoaderRoute: typeof AdminPurchasesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/paymentmethods': {
      id: '/admin/paymentmethods'
      path: '/paymentmethods'
      fullPath: '/admin/paymentmethods'
      preLoaderRoute: typeof AdminPaymentmethodsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/locations': {
      id: '/admin/locations'
      path: '/locations'
      fullPath: '/admin/locations'
      preLoaderRoute: typeof AdminLocationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ledger': {
      id: '/admin/ledger'
      path: '/ledger'
      fullPath: '/admin/ledger'
      preLoaderRoute: typeof AdminLedgerRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/journal': {
      id: '/admin/journal'
      path: '/journal'
      fullPath: '/admin/journal'
      preLoaderRoute: typeof AdminJournalRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/items': {
      id: '/admin/items'
      path: '/items'
      fullPath: '/admin/items'
      preLoaderRoute: typeof AdminItemsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cashboxes': {
      id: '/admin/cashboxes'
      path: '/cashboxes'
      fullPath: '/admin/cashboxes'
      preLoaderRoute: typeof AdminCashboxesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/batches': {
      id: '/admin/batches'
      path: '/batches'
      fullPath: '/admin/batches'
      preLoaderRoute: typeof AdminBatchesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/accounts': {
      id: '/admin/accounts'
      path: '/accounts'
      fullPath: '/admin/accounts'
      preLoaderRoute: typeof AdminAccountsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAccountsRoute: typeof AdminAccountsRoute
  AdminBatchesRoute: typeof AdminBatchesRoute
  AdminCashboxesRoute: typeof AdminCashboxesRoute
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminItemsRoute: typeof AdminItemsRoute
  AdminJournalRoute: typeof AdminJournalRoute
  AdminLedgerRoute: typeof AdminLedgerRoute
  AdminLocationsRoute: typeof AdminLocationsRoute
  AdminPaymentmethodsRoute: typeof AdminPaymentmethodsRoute
  AdminPurchasesRoute: typeof AdminPurchasesRoute
  AdminSalesRoute: typeof AdminSalesRoute
  AdminSuppliersRoute: typeof AdminSuppliersRoute
  AdminTransfersRoute: typeof AdminTransfersRoute
  AdminUnitsRoute: typeof AdminUnitsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAccountsRoute: AdminAccountsRoute,
  AdminBatchesRoute: AdminBatchesRoute,
  AdminCashboxesRoute: AdminCashboxesRoute,
  AdminCustomersRoute: AdminCustomersRoute,
  AdminItemsRoute: AdminItemsRoute,
  AdminJournalRoute: AdminJournalRoute,
  AdminLedgerRoute: AdminLedgerRoute,
  AdminLocationsRoute: AdminLocationsRoute,
  AdminPaymentmethodsRoute: AdminPaymentmethodsRoute,
  AdminPurchasesRoute: AdminPurchasesRoute,
  AdminSalesRoute: AdminSalesRoute,
  AdminSuppliersRoute: AdminSuppliersRoute,
  AdminTransfersRoute: AdminTransfersRoute,
  AdminUnitsRoute: AdminUnitsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
